### ISSUE TITLE
Finalize email content

### ISSUE THREAD

**Issue by revgum** [osulp/Easydeposit2#107]
- [ ] Claim work 
- [ ] Published work

We need to nail down the look, feel, and content of these emails

**Comment by revgum** [comment]
@vantuyls here's an example of the Published Work Email:

# Your work has been published by some_user@email.address

### Some Title Here
### A Second Title Here

Repository: https://scholars_archive/link/to/work
Easy Deposit: https://server/link/to/view/publication

**Comment by vantuyls** [comment]
## Subject
Please deposit your recent article in ScholarsArchive@OSU

## Body
Dear <author>,

Congratulations on your new publication - <title>. As you may know, the Faculty Senate at Oregon State University passed an Open Access Policy in June 2013 <http://cdss.library.oregonstate.edu/sites/default/files/osu_openacesspolicy_final_single_page.pdf>. As part of this policy, faculty are asked to deposit their journal articles into ScholarsArchive@OSU to make OSU's research publicly available and to increase the reach and impact of our research. 

To this end, we invite you to deposit your article using this link:
<link to record>

Once there, you may upload your article and, if needed, make corrections to the metadata on the record for your article. For guidance on the version of the article you are allowed to upload, please see our deposit guide. <https://guides.library.oregonstate.edu/Scholars-Archive/FacultyArticles>

If you have any questions, please follow up with us at scholarsarchive@oregonstate.edu

Best, 

The OSU Libraries Digital Repository Team

**Comment by vantuyls** [comment]
## Subject
Thank you for depositing your article in ScholarsArchive@OSU

## Body
Dear <author>, 

Thank you for depositing your article, <title>, in ScholarsArchive@OSU. The permanent URL for your article is: <theURL>

If you have any further questions, concerns, or feedback about your experience with ScholarsArchive@OSU or the OSU Open Access Policy, please contact us at scholarsarchive@oregonstate.edu. 

Best, 

The OSU Libraries Digital Repository Team

**Comment by vantuyls** [comment]
feedback welcome.

**Comment by simholt** [comment]
**BOLD** is recommended removal.
_Italix_ is to add.
<hr>
Dear ,

Congratulations on your new publication - <title>. **As you may know,** The Faculty Senate at Oregon State University passed an Open Access Policy in June 2013 http://cdss.library.oregonstate.edu/sites/default/files/osu_openacesspolicy_final_single_page.pdf. As part of this policy, faculty are asked (REQUIRED?) to deposit their journal articles into ScholarsArchive@OSU to make OSU's research publicly available and to increase the reach and impact of our research.

**To this end,** We invite you to deposit your article using this link:

Once there, you may upload your article and**, if needed,** make corrections to the metadata **on the record for your article**. For guidance on the version of the article you are allowed to upload, **please** see our deposit guide. https://guides.library.oregonstate.edu/Scholars-Archive/FacultyArticles

**If you have any questions,** _Questions_? Please follow up with us at scholarsarchive@oregonstate.edu

**Best** _Sincerely_,

The OSU Libraries Digital Repository Team
