### ISSUE TITLE
ED2 should check SA@OSU to see if the item has already been deposited

### ISSUE THREAD

**Issue by vantuyls** [osulp/Easydeposit2#11]
this will help reduce duplicate deposits.

**Comment by zhang4952** [comment]
Before depositing the metadata records into SA, make sure that article has not been deposited already.

**Comment by zhang4952** [comment]
Use `DOI` field in article model, see #4

**Comment by vantuyls** [comment]
we definitely have a use case where the may not be a DOI for an article - a faculty member who independently  chooses to upload their article to SA@OSU may not enter the DOI for their article. 

as MVP, a DOI match may be fine, but in that case, i think we need to have some validation of the DOI on the form, so that the depositor enters the DOI in the correct format for matching.

**Comment by revgum** [comment]
It was decided to query the catalog for any work that has the wos uid metadata.
