### ISSUE TITLE
#show view cleanup

### ISSUE THREAD

**Issue by revgum** [osulp/Easydeposit2#122]
### Descriptive summary

For an administrator, it seems that the full show page has plenty of information. But a non-administrator might only need a subset of this data. 

### Expected behavior

- [x] As a non-admin, hide "(fingerprint) ...." span
- [x] As a non-admin, hide processed events partials

Refer to screenshot

![screen shot 2018-08-22 at 11 17 56 am](https://user-images.githubusercontent.com/32885/44482612-b6623b00-a5fd-11e8-89d9-8c681663f510.png)

**Comment by simholt** [comment]
Yes to both.

**Comment by revgum** [comment]
non-admin users should not see the processed events partials
