### ISSUE TITLE
Source feed configuration for data serialization

### ISSUE THREAD

**Issue by revgum** [osulp/Easydeposit2#13]
For instance, PubMed is using RSS 2.0: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1vKcRI80qSZYSfEs8OHtZ9BnatCpFFoPkEKLKqH7e0cWmg6kvK (view the source of the page)

**Comment by zhang4952** [comment]
N/A, we are using WoS API not feeds
