### ISSUE TITLE
Replace OA Policy Link with updated version

### ISSUE THREAD

**Issue by vantuyls** [osulp/Easydeposit2#157]
### Descriptive summary
ED2 emails include a link to the OSU Faculty Senate Open Access Policy. The link used is dated (on a legacy OSULP website). The faculty senate has the OA Policy on their website and we should use that link. 

https://senate.oregonstate.edu/sites/senate.oregonstate.edu/files/openaccesspolicy_june2013.pdf

**Comment by zhang4952** [comment]
This will be reflected in the article recruit email.

**Comment by zhang4952** [comment]
fix by #177
