### ISSUE TITLE
authenticate user by hashed_email

### ISSUE THREAD

**Issue by revgum** [osulp/Easydeposit2#175]
### Descriptive summary

The publications controller needs to "login" the associated user when the claim link is used. This bypasses the regular user authentication and logs in the user associated with claim_link passed in on the query parameters.

### Expected behavior

**In PublicationsController**
- [x] Add `skip_before_action :authenticate_user!, only: [:claim]`
- [x] Add `before_action :login_claim_link_user, only: [:claim]`
- [x] Create login_claim_link_user method, find the user related to the AuthorPublication with the associated `claim_link` from params
- [x] Login the user found in the previous step (`sign_in(@user)`)

**Comment by zhang4952** [comment]
fix by #176
