### ISSUE TITLE
Title not show in stats view

### ISSUE THREAD

**Issue by zhang4952** [osulp/Easydeposit2#212]
### Descriptive summary

Articles deposited to SA through ED2 shows "No Title" in breadcrumbs and on the Analytics show page. See screen shot below.
<img width="1191" alt="screen shot 2018-11-14 at 10 33 19 am" src="https://user-images.githubusercontent.com/609011/48519019-450ede80-e820-11e8-8872-addefcc96627.png">

### Expected behavior

Make sure article title show in Work statistics view and breadcrumbs.

**Comment by simholt** [comment]
Related: I noticed that after clicking Edit, "no title" shows up on the top tab. The title appears after the item has been saved -- both on the tab and on the analytics page.
- - - - 
Before:
![screen shot 2019-02-22 at 12 44 48 pm](https://user-images.githubusercontent.com/33705514/53270322-49108f00-36a0-11e9-82f1-d69ec23954d7.png)

After:
![screen shot 2019-02-22 at 12 45 17 pm](https://user-images.githubusercontent.com/33705514/53270333-53328d80-36a0-11e9-9a28-32e14702230d.png)

![screen shot 2019-02-22 at 12 50 12 pm](https://user-images.githubusercontent.com/33705514/53270406-7cebb480-36a0-11e9-82ee-0a601d91af4c.png)

**Comment by zhang4952** [comment]
fixed via #226
