### ISSUE TITLE
Creator not always listed on search results page

### ISSUE THREAD

**Issue by simholt** [osulp/Easydeposit2#217]
### Descriptive summary
Although ED2 items have creators, they are usually not listed on the search results page.

### Expected behavior
![screen shot 2019-02-05 at 1 27 31 pm](https://user-images.githubusercontent.com/33705514/52305418-e8681f00-2949-11e9-9353-1ab32465a0c7.png)

### Actual behavior
![screen shot 2019-02-05 at 1 25 17 pm](https://user-images.githubusercontent.com/33705514/52305425-ec943c80-2949-11e9-85e5-6b2a8b0a0609.png)

### Steps to reproduce the behavior
1. Click Go on SA search bar.
2. Click Resource type & facet by article.
3. [Or just click here](https://ir.library.oregonstate.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=Article&locale=en&q=&search_field=all_fields).
- - - -
Creator not showing up:
https://ir.library.oregonstate.edu/concern/articles/9019s813b
https://ir.library.oregonstate.edu/concern/articles/z029pb237
https://ir.library.oregonstate.edu/concern/articles/m900p099b

Creator showing up:
https://ir.library.oregonstate.edu/concern/articles/zk51vn86m
https://ir.library.oregonstate.edu/concern/articles/ht24wq62r

**Comment by simholt** [comment]
See related comment on #218.

**Comment by zhang4952** [comment]
fixed via #226
