### ISSUE TITLE
Abstract not always listed on results page

### ISSUE THREAD

**Issue by simholt** [osulp/Easydeposit2#218]
### Descriptive summary
Although ED2 items have abstracts, they are usually not listed on the search results page.

### Expected behavior
![screen shot 2019-02-05 at 1 27 31 pm](https://user-images.githubusercontent.com/33705514/52305418-e8681f00-2949-11e9-9353-1ab32465a0c7.png)

### Actual behavior
![screen shot 2019-02-05 at 1 25 17 pm](https://user-images.githubusercontent.com/33705514/52305425-ec943c80-2949-11e9-85e5-6b2a8b0a0609.png)

### Steps to reproduce the behavior
1. Click Go on SA search bar.
2. Click Resource type & facet by article.
3. [Or just click here](https://ir.library.oregonstate.edu/catalog?f%5Bresource_type_sim%5D%5B%5D=Article&locale=en&q=&search_field=all_fields).
- - - -
Abstract not showing up:
https://ir.library.oregonstate.edu/concern/articles/9019s813b
https://ir.library.oregonstate.edu/concern/articles/z029pb237
https://ir.library.oregonstate.edu/concern/articles/m900p099b

Abstract showing up:
https://ir.library.oregonstate.edu/concern/articles/zk51vn86m
https://ir.library.oregonstate.edu/concern/articles/ht24wq62r

**Comment by simholt** [comment]
FYI - Abstract (and other fields) show up properly after clicking edit & then save (without changing anything).
- - - - 
Before:
![screen shot 2019-02-22 at 12 44 31 pm](https://user-images.githubusercontent.com/33705514/53270197-ea4b1580-369f-11e9-810c-d421feab9b0a.png)

After:
![screen shot 2019-02-22 at 12 45 07 pm](https://user-images.githubusercontent.com/33705514/53270201-f040f680-369f-11e9-8e8e-e240f67fa8c0.png)

**Comment by zhang4952** [comment]
Hint: it could means that we should run a Solr index update after ingestion from ED2. The same may apply to #217, #212

**Comment by zhang4952** [comment]
fixed via #226
