### ISSUE TITLE
Build rake task to ingest WoS data from TSV

### ISSUE THREAD

**Issue by CGillen** [osulp/Easydeposit2#249]
### Descriptive summary
A rake task to ingest from WoS search TSV dump will be an interim solution to get ED2 ingesting articles again. This can also be used during any other periods of breakage or during other transitions.

![IMG_20200312_135241](https://user-images.githubusercontent.com/11052958/76567111-55ae8380-646b-11ea-847b-a60d18c759a3.jpg)

The workflow:
- Read TSV into Array of Hashes
- Convert into [WebOfScience::Records](https://github.com/osulp/Easydeposit2/blob/master/lib/web_of_science/records.rb), you can use this to base the conversion from TSV data off of: https://github.com/osulp/Easydeposit2/blob/feature/RESTBackend/lib/web_of_science/records.rb#L38-L115
- Pass Records into WebOfScience::ProcessRecords and execute. Similar to: https://github.com/osulp/Easydeposit2/blob/feature/RESTBackend/lib/web_of_science/harvester.rb#L35
- This creates all the Publications and returns the UIDs.
  - Creating the Publications kicks off the FetchAuthor job which will fail and dead end. Ignore this
- From the UIDs, find the Publications again, call add_author_email on each publication with the data from the TSV. The data should look like this: https://github.com/osulp/Easydeposit2/blob/master/app/jobs/fetch_authors_directory_api_job.rb#L78-L84
- On each Publication, call recruit_author! as this:https://github.com/osulp/Easydeposit2/blob/master/app/jobs/fetch_authors_directory_api_job.rb#L34
  - This will kick off the author emailing job.

### Expected behavior
From TSV data, emails should go out to authors & the proper EasyDeposit data structures should be added to the database.

### Related work
Interim to RESTful API usage.

**Comment by zhang4952** [comment]
- update abstract: https://github.com/osulp/Easydeposit2/blob/0b23ecc61e88acc724073f2273d5e767e06b7f25/app/jobs/fetch_wos_content_job.rb#L25
- add author email: https://github.com/osulp/Easydeposit2/blob/0b23ecc61e88acc724073f2273d5e767e06b7f25/app/jobs/fetch_wos_content_job.rb#L54

**Comment by zhang4952** [comment]
Closed via PR #259  #250
