### ISSUE TITLE
Metadata mapping for each source

### ISSUE THREAD

**Issue by revgum** [osulp/Easydeposit2#7]
Build a configuration to map from a source fields to SA work type property

**Comment by zhang4952** [comment]
ED2 will use WoS API to pull publications, we can start with the MAP created for feeds for metadata mapping: https://docs.google.com/spreadsheets/d/1ghLTfvMiqxouN4p3FEB7aq9bZwVFYooDkPbUJgPrkz0/edit?usp=sharing

**Comment by revgum** [comment]
done
